[package]
name = "quickly"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/rust/lib.rs"

[dependencies]
wasm-bindgen = "0.2.85"

[dependencies.web-sys]
version = "0.3.75"
features = [
    "console",
]
